# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 14:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oper', '0002_auto_20170407_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
