# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 14:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oper', '0003_produto_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
