# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oper', '0005_produto_client_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(null=True, verbose_name='Descri\xe7\xe3o')),
                ('qtd', models.IntegerField(verbose_name='Quantidade')),
                ('when_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('when_updated', models.DateTimeField(auto_now=True, null=True)),
                ('client_ip', models.GenericIPAddressField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto_del', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
