# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 13:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oper', '0010_auto_20170411_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='qtd',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Quantidade'),
        ),
    ]
